### ISSUE TITLE
Question about the final XCFramework

### ISSUE THREAD

**Issue by intonarumori** [balthisar/openssl-xcframeworks#1]
I'm trying to wrap my head around this repository.
I need to integrate OpenSSL into a Catalyst Mac app and this seems to do the trick.
However it's not clear how to get the final `XCFramework` folder/package.

What I did:
` ./build-libssl.sh --version=1.0.2k`
`create-openssl-framework.sh static`

I have the frameworks but nothing with `XCFramework`, any tip where should I look?

Many thanks.

**Comment by ghost** [comment]
You have to use the command ./create-openssl-framework.sh xcstatic to get the XCFramework! Afterwards, it will be in the frameworks-folder.
